"""Control definitions for the opt-in scan and CRT operations."""


def modules(Module, P):
    return (
        Module('scan_modulation', 'Scan modulation', 'Key an image region and interrupt its signal with coupled row oscillators, color-lock faults and bright phosphor points.', (
            P('input', 'Signal input', 0, 0, 1, 1, 'Original source samples imported footage before Subject cutout and color treatment. For generated objects it samples the untreated object.', choices=('Current image', 'Original source')),
            P('region', 'Region', 0, 0, 2, 1, choices=('Whole image', 'Highlights', 'Color range')),
            P('key_hue', 'Selected hue', .06, 0, 1, .01),
            P('key_width', 'Hue tolerance', .09, 0, .5, .01),
            P('key_saturation', 'Minimum saturation', .12, 0, .9, .01),
            P('key_floor', 'Minimum brightness', .08, 0, .9, .01),
            P('key_softness', 'Selection softness', .12, .01, .5, .01),
            P('key_invert', 'Invert selection', 0, 0, 1, 1, choices=('Off', 'On')),
            P('show_key', 'View', 0, 0, 1, 1, 'Selection view shows white where the effect applies, useful when changing source footage.', choices=('Result', 'Selection')),
            P('fade', 'Directional fade', 0., 0, 1, .01),
            P('fade_start', 'Fade start', .72, -.5, 1.5, .01, 'Distance along the fade direction. 0.5 is the canvas center.'),
            P('fade_width', 'Fade softness', .2, .01, 1, .01),
            P('fade_angle', 'Fade direction', 0., -180, 180, 1, 'Zero fades toward the bottom, 90 degrees toward the right.'),
            P('row_pitch', 'Row spacing', 4.5, 1, 30, .25, 'Pixels at a 720-pixel reference edge.'),
            P('irregularity', 'Row irregularity', .5, 0, 1, .01),
            P('wave', 'Oscillator displacement', 18., 0, 180, 1),
            P('tear', 'Irregular displacement', 35., 0, 240, 1),
            P('streak', 'Signal trails', 25., 0, 200, 1),
            P('depth', 'Row interruption', .85, 0, 1, .01),
            P('dropout', 'Dark rows', .5, 0, 1, .01),
            P('rate', 'Modulation speed', 1., 0, 5, .05, 'Zero freezes the modulation while source footage keeps playing.'),
            P('cadence', 'Modulation FPS', 0., 0, 60, 1, 'Zero gives continuous oscillators. Color failures and row noise retain their own signal clock.'),
            P('black', 'Signal black point', .04, 0, .9, .01),
            P('white', 'Signal white point', .65, .1, 1.5, .01),
            P('hue', 'Signal hue', .51, 0, 1, .01),
            P('saturation', 'Signal saturation', .8, 0, 1, .01),
            P('exposure', 'Signal exposure', .5, -3, 3, .05),
            P('color_faults', 'Color-lock failures', .65, 0, 1, .01),
            P('fragment_width', 'Color fragment width', 45., 3, 300, 1),
            P('sparks', 'Bright point density', .35, 0, 1, .01),
            P('spark_size', 'Bright point size', 2.5, .5, 10, .25),
            P('spark_threshold', 'Bright point threshold', .45, 0, 1, .01),
            P('spark_gain', 'Bright point intensity', 2., 0, 5, .1),
            P('spark_fade', 'Fade points downward', 0., 0, 1, .01),
            P('spark_end', 'Point fade start', .25, 0, 1, .01, 'Fraction of canvas height; active when Fade points downward is above zero.'),
            P('mix', 'Mix', 1., 0, 1, .01),
        )),
        Module('crt_capture', 'CRT capture', 'Curved phosphor interference, optical softness and exposure drift across the complete canvas.', (
            P('pitch', 'Phosphor spacing', 3., 1, 12, .25, 'Pixels at a 720-pixel reference edge. Fine columns fade below preview resolution.'),
            P('phosphor', 'Phosphor depth', .18, 0, 1, .01),
            P('moire', 'Camera moiré', .22, 0, 1, .01),
            P('moire_pitch', 'Moiré spacing', 24., 4, 160, 1),
            P('angle', 'Screen angle', 2., -90, 90, .5),
            P('curvature', 'Moiré curvature', 1.5, 0, 8, .1),
            P('weave', 'Moiré irregularity', .4, 0, 1, .01),
            P('field', 'Uneven phosphor field', .15, 0, 1, .01),
            P('bend', 'Raster instability', 1.5, 0, 20, .1),
            P('drift', 'Moiré drift', .6, 0, 5, .05),
            P('softness', 'Lens softness', .65, 0, 5, .05),
            P('focus_drift', 'Focus breathing', 1.4, 0, 12, .1),
            P('exposure', 'Screen exposure', .3, -3, 3, .05),
            P('flicker', 'Exposure instability', .3, 0, 1, .01),
            P('grain', 'Emitted-light grain', .05, 0, .4, .01),
            P('halation', 'Light spill', .25, 0, 2, .01),
            P('threshold', 'Light spill threshold', .5, 0, 1, .01),
            P('radius', 'Light spill radius', 4., .5, 30, .5),
            P('rate', 'Capture drift speed', 1., 0, 5, .05),
            P('cadence', 'Capture FPS', 25., 0, 60, 1, 'Zero gives continuous drift. Capture drift speed zero freezes all screen behavior.'),
            P('mix', 'Mix', 1., 0, 1, .01),
        )),
    )
